services:
  n8n:
    image: n8nio/n8n
    container_name : n8n
    ports:
      - "5678:5678"
    environment:
      - WEBHOOK_URL=http://localhost:5678/ 
    volumes:
      - n8n_data:/home/node/.n8n  # Persist n8n data

volumes:
  n8n_data:
  
  